/run/numberOfThreads 1

/control/verbose 1
#/control/cout/useBuffer
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

#Detector

#Physics
# /testem/phys/addPhysics emlivermore
#/testem/phys/addPhysics empenelope
#/process/eLoss/CSDARange true
#/run/setCut 100 nm
#/testem/phys/setCuts 1 um
#/cuts/setLowEdge 30 keV
/cuts/setLowEdge 5 MeV

/run/initialize

#  /process/em/deexcitation Target true true true
#  /process/em/fluo true
#  /process/em/auger true
#  /process/em/pixe true
#  /process/em/deexcitationIgnoreCut true

#/process/em/pixeXSmodel Empirical
#/process/em/pixeXSmodel ECPSSR_FormFactor
#/process/em/pixeXSmodel ECPSSR_Analytical
#/process/em/pixeElecXSmodel Penelope
# /process/em/pixeElecXSmodel Livermore

# Set guns
#//  /gun/particle e-
#//  /gun/energy 10 GeV
#//  /gun/position 0. 0. -50. um
#//  /gun/direction 0. 0. 1.

# Set analysis axis
/analysis/setFileName proba2
/analysis/h1/set 1    1000  0.0   50  keV #Edep in target [MeV]
/analysis/h1/setXaxis 1 "Energy [MeV]"
/analysis/h1/setYaxis 1 "Number of particles"
/analysis/h1/setAscii 1

/analysis/h1/set 2    1000  0.0   8.0  MeV #Gamma spectra at detector [MeV]
/analysis/h1/setXaxis 2 "Energy [MeV]"
/analysis/h1/setYaxis 2 "Number of particles"
/analysis/h1/setAscii 2

/analysis/h1/set 3    360  0.0  180.0  degree #Gamma distribution in YZ plane [degree]
/analysis/h1/setXaxis 3 "Angle [degree]"
/analysis/h1/setYaxis 3 "Number of particles"
/analysis/h1/setAscii 3

/analysis/h1/set 4    4000  0.0   10000.0  MeV #Electron spectra [MeV]
/analysis/h1/setXaxis 4 "Energy [MeV]"
/analysis/h1/setYaxis 4 "Number of electrons"
/analysis/h1/setAscii 4

/analysis/h1/set 5    4000  0.0   10000.0  MeV #Positron spectra [MeV]
/analysis/h1/setXaxis 5 "Energy [MeV]"
/analysis/h1/setYaxis 5 "Number of positrons"
/analysis/h1/setAscii 5


/analysis/h2/set 1    100  -.01   .01    m  none  linear 100 -.01   .01   m  none linear #Source spectra [MeV]
/analysis/h2/setXaxis 1 "Position X [m]"
/analysis/h2/setYaxis 1 "Position Y [m]"
# /analysis/h2/setAscii 1 true

/analysis/h2/set 2    100  -.01   .01  rad  none  linear 100 -.01   .01  rad  none linear #Source spectra [MeV]
/analysis/h2/setXaxis 2 "Theta_X [rad]"
/analysis/h2/setYaxis 2 "Theta_Y [rad]"

/analysis/h2/set 3    100  .0   .35    m  none  linear 100 -.1   .1   m  none linear #Source spectra [MeV]
/analysis/h2/setXaxis 3 "Position X [m]"
/analysis/h2/setYaxis 3 "Position Y [m]"
# /analysis/h2/setAscii 1 true

/analysis/h2/set 4    100  .00   .52  rad  none  linear 100 -.01   .01  rad  none linear #Source spectra [MeV]
/analysis/h2/setXaxis 4 "Theta_X [rad]"
/analysis/h2/setYaxis 4 "Theta_Y [rad]"

/analysis/h2/set 5    100  -.35  -.0    m  none  linear 100 -.1   .1   m  none linear #Source spectra [MeV]
# /analysis/h2/set 5    100  -.01   .01    m  none  linear 100  -.01   .01   m  none linear #Source spectra [MeV]
/analysis/h2/setXaxis 5 "Position X [m]"
/analysis/h2/setYaxis 5 "Position Y [m]"
# /analysis/h2/setAscii 1 true

/analysis/h2/set 6    100  -.52   -.0  rad  none  linear 100 -.01   .01  rad  none linear #Source spectra [MeV]
/analysis/h2/setXaxis 6 "Theta_X [rad]"
/analysis/h2/setYaxis 6 "Theta_Y [rad]"


/run/printProgress 300000
/run/beamOn 300000
